dist: bionic
addons:
  chrome: stable
  apt:
    packages:
      - libnss3
      # These are required to run webkit
      - libwoff1
      - libopus0
      - libwebp6
      - libwebpdemux2
      - libenchant1c2a
      - libgudev-1.0-0
      - libsecret-1-0
      - libhyphen0
      - libgdk-pixbuf2.0-0
      - libegl1
      - libgles2
      - libevent-2.1-6
      - libnotify4
      - libxslt1.1
      - libvpx5
      # This is required to run chromium
      - libgbm1
      # this is needed for running headful tests
      - xvfb

language: node_js
sudo: false

node_js:
  - '12'

before_install:
  # Info about OS
  - uname
  - if [[ `node -v` = v6* ]]; then npm i -g npx; fi
  - npx --version
  # Launch XVFB
  - if [[ `uname` = "Linux" ]]; then export DISPLAY=:99.0; fi

script:
  - node --version
  - npm --version
  - npx --version
  - npm run build
  - if [[ `uname` = "Linux" ]]; then xvfb-run --auto-servernum npm test; else npm test; fi

os:
  - linux
  - osx

osx_image: xcode11.3
