environment:
  matrix:
    - nodejs_version: '12'

install:
  - ps: >
      if ($env:nodejs_version -eq "12") {
        Install-Product node $env:nodejs_version x64
      } else {
        Install-Product node $env:nodejs_version
      }
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

matrix:
  fast_finish: false
build: off
shallow_clone: true
test_script:
  - node --version
  - npm --version
  - npx --version
  - npm run build
  - npm test
cache:
  - '%APPDATA%\npm-cache'
