// this file was auto-generated by 'generator/create-steps-mappings.ts'
// tslint:disable:max-line-length
import * as step from './steps';

export interface IStepMappings {
  [index: string]: (stepname: string) => Promise<any>;
}
// tslint:disable:object-literal-sort-keys
export const givenStepMappings = {
  'I enter my name': step.iEnterMyName,
  'I navigate to the testcafe sample page': step.iNavigateToTheTestcafeSamplePage,
};
export type GivenStep = keyof typeof givenStepMappings;
// tslint:disable:object-literal-sort-keys
export const whenStepMappings = {
  'I do something specific': step.iDoSomethingSpecific,
  'I enter my name': step.iEnterMyName,
  'I navigate to the testcafe sample page': step.iNavigateToTheTestcafeSamplePage,
  'I send my feedback on testcafe': step.iSendMyFeedbackOnTestcafe,
};
export type WhenStep = keyof typeof whenStepMappings;
// tslint:disable:object-literal-sort-keys
export const thenStepMappings = {
  "a 'Thank you' message should appear with my name": step.aXxxMessageShouldAppearWithMyName,
  'I can submit my feedback on testcafe': step.iCanSubmitMyFeedbackOnTestcafe,
  'I cannot submit my feedback on testcafe': step.iCannotSubmitMyFeedbackOnTestcafe,
  'no name should be populated': step.noNameShouldBePopulated,
};
export type ThenStep = keyof typeof thenStepMappings;
export const butStepMappings = {};
export type ButStep = keyof typeof butStepMappings;
