// this file was auto-generated by 'generator/create-steps-barrel.ts'
// tslint:disable:max-line-length
export { default as aXxxMessageShouldAppearWithMyName } from '../steps/a-xxx-message-should-appear-with-my-name';
export { default as iCanSubmitMyFeedbackOnTestcafe } from '../steps/i-can-submit-my-feedback-on-testcafe';
export { default as iCannotSubmitMyFeedbackOnTestcafe } from '../steps/i-cannot-submit-my-feedback-on-testcafe';
export { default as iDoSomethingSpecific } from '../steps/i-do-something-specific';
export { default as iEnterMyName } from '../steps/i-enter-my-name';
export { default as iNavigateToTheTestcafeSamplePage } from '../steps/i-navigate-to-the-testcafe-sample-page';
export { default as iSendMyFeedbackOnTestcafe } from '../steps/i-send-my-feedback-on-testcafe';
export { default as noNameShouldBePopulated } from '../steps/no-name-should-be-populated';
